#!/usr/bin/ruby

exclude_files = [ 'install', 'Capfile', 'REVISION' ]
base_path = File.expand_path( File.dirname( __FILE__) )

files = Dir[ File.join( base_path, '*' ) ]
files.each do |source_path|
  file = File.basename( source_path )
  next if exclude_files.include? file
  dest_path = File.expand_path( '~/.' + file )

  if File.exists? dest_path
    if File.symlink? dest_path
      if File.readlink( dest_path ) == source_path
        puts "Symlink already in place for #{dest_path}"
      else
        puts "ERROR: #{dest_path} is linked to #{File.readlink( dest_path )}"
        if `diff #{dest_path} #{source_path}`.empty?
          puts "Files are identical. Overwriting."
          res = `rm #{dest_path}`
          puts res unless res.empty?
          res = `ln -s #{source_path} #{dest_path}`
          puts res unless res.empty?
        end
      end
    else
      puts "ERROR: #{dest_path} already exists"
      if `diff #{dest_path} #{source_path}`.empty?
        puts "Files are identical. Overwriting."
        res = `rm #{dest_path}`
        puts res unless res.empty?
        res = `ln -s #{source_path} #{dest_path}`
        puts res unless res.empty?
      end
    end
  else
    puts "Linking #{dest_path}"
    puts `ln -s #{source_path} #{dest_path}`
  end
end
