#!/usr/bin/ruby

exclude_files = [ 'install', 'Capfile' ]

files = Dir['*']
files.each do |file|
  next if exclude_files.include? file
  source_path = File.expand_path( './' + file )
  dest_path = File.expand_path( '~/.' + file )

  if File.exists? dest_path
    if File.symlink? dest_path
      if File.readlink( dest_path ) == source_path
        # we're good
      else
        puts "ERROR: #{dest_path} is linked to #{File.readlink( dest_path )}"
      end
    else
      puts "ERROR: #{dest_path} already exists"
    end
  else
    puts "Linking #{dest_path}"
    puts `ln -s #{source_path} #{dest_path}`
  end
end
